### ISSUE TITLE
Epic: Tensorflow & Keras tutorial

### ISSUE THREAD

**Issue by kadamQ** [EKU-Summer-2021/dl-assignment-saidsabri010#1]
As a manager, I want the developer to understand how modern data processing and deep learning works.
As a developer, I want to receive working implementations of deep feed forward, sequence processing, and image recognition networks.
As a manager, I want to be able to quantify the performance of the networks.
As a developer, I want to be able to run the models with parameters from a configuration file.
As a manager, I want to be able to look at plots visualizing the output of the model.

__AC__:
- [ ] complete tensorflow tutorial
- [ ] read CSV into pandas dataframe
- [ ] log model runs and solutions
- [ ] plot outputs
- [ ] print best model parameters
- [ ] save run data into directory with separate names

__Story Point:__ 5
